### PR TITLE
Add new extractor for Bluecoders.io (http://bluecoders.io/)

### PR DESCRIPTION
**Pull request by CkuT**
Also adds a dependency to parsedatetime lib in order to parse natural dates

### CODE REVIEW

**Comment by lebouquetin** [comment]
Thanks for your contribution, CkuT

**Comment by lebouquetin** [comment]
@CkuT that would be very nice if you add the "address" property (this is the content of <span> just after <span class="zmdi zmdi-pin">)

A trainee is finishing a dev task which integrates geoloc/geosearch of job opportunities on pyjobs. It is based on address, so it would be very nice to add this for bluecoders.io :-)

**Comment by CkuT** [comment]
It seems the city is the only information available. Is it enough for you ?
See here : 1db9776

**Comment by lebouquetin** [comment]
Yes, that's fine

**Pull request merged**
